### ISSUE TITLE
ImportError: cannot import name display_prop_borders

### ISSUE THREAD

**Issue by TimFruition** [mthh/gpd_lite_toolbox#1]
Hello,

I tried gpd_lite_toolbox, but I couldn't install due to `ImportError: cannot import name display_prop_borders`. I quickly watched gpd_lite_toolbox core code and it comes from utils. But my utils is up to date.

Have you an idea how to solve this ?

**Comment by mthh** [comment]
Hi!

Thanks for reporting this issue. I fixed it (in ef76ed2) but please, dont have have too much expectations about the functions available in this repository; it's just a few functions (that I found useful at this point) written when I needed to use geopandas (some of them have been very little tested!)

Cheers
